apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "postgres-xl-operator.serviceAccountName" . }}-role
  labels:
  {{ include "postgres-xl-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
#  - apiGroups: [""]
#    resources: ["pods"]
#    verbs: ["get", "watch", "list"]