apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "postgres-xl-operator.serviceAccountName" . }}-role
  labels:
  {{ include "postgres-xl-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "postgres-xl-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "postgres-xl-operator.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
