{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres-xl-operator.serviceAccountName" . }}
  labels:
{{ include "postgres-xl-operator.labels" . | nindent 4 }}
{{- end -}}
