apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgres-xl-clusters.{{CUSTOM_RESOURCE_GROUP}}
spec:
  group: {{CUSTOM_RESOURCE_GROUP}}
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: postgres-xl-clusters
    singular: postgres-xl-cluster
    kind: PostgresXlCluster