apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{CLUSTER_RESOURCE_PLURAL}}.{{CUSTOM_RESOURCE_GROUP}}
spec:
  group: {{CUSTOM_RESOURCE_GROUP}}
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: {{CLUSTER_RESOURCE_PLURAL}}
    singular: {{CLUSTER_RESOURCE_SINGULAR}}
    kind: {{CLUSTER_RESOURCE_KIND}}