#!/usr/bin/env bash
# Coordinator initialization script
cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"

# initialize dependecies.
source "$cur_path/initialize_env_dependencies" || exit $?

if [ -z "$MASTER_NAME" ]; then
  log:info "Starting postgres as master coordinator"
  # initialize the database.
  source "$cur_path/initialize_postgres_db" || exit $?
  # start the node register in the bg.
  "$cur_path/register_node" &
else
  log:info "Starting postgres as standby coordinator"
  # initialize the database.
  source "$cur_path/initialize_standby_coordinator" || exit $?
fi

# starting postgres.
postgres \
    -D "${PGDATA}" \
    -h "${PG_HOST}" \
    -p "${PG_PORT}" \
    -c gtm_host="${PG_GTM_HOST}" \
    -c gtm_port="${PG_GTM_PORT}" \
    --coordinator
