#!/usr/bin/env bash

MASTER_SERVICE="$MASTER_NAME-dn-$((POD_CLUSTER_INDEX-1)).$MASTER_NAME-svc-dn"

# waiting for master datanode.
"$cur_path/wait_for_connection" "$MASTER_SERVICE" "$PG_PORT"
assert $? "Error while waiting for connection. Deployment not ready." || exit $?

pg_basebackup -d "postgresql://$PGUSER:$PGPASSWORD@$MASTER_SERVICE:$PG_PORT" -D "$PGDATA" -P --wal-method=stream

echo "standby_mode          = 'on'" > "$PGDATA/recovery.conf"
echo "primary_conninfo      = 'host=$MASTER_SERVICE port=$PG_PORT user=$PGUSER password=$PGPASSWORD'" >> "$PGDATA/recovery.conf"
echo "trigger_file          = '/tmp/MasterNow'" >> "$PGDATA/recovery.conf"
echo "hot_standby = on" >> "$PGDATA/postgresql.conf"