apiVersion: v1
kind: Secret
metadata:
  name:  pgxl-passwords-collection
type: Opaque
data:
  # You must byte64 encode your values. See: https://kubernetes.io/docs/concepts/configuration/secret/
  # the password is: "this_is_not_a_password"
  pgpass: dGhpc19pc19ub3RfYV9wYXNzd29yZA==
---
apiVersion: {{CUSTOM_RESOURCE_GROUP}}/v1
kind: {{CLUSTER_RESOURCE_KIND}}
metadata:
  name: {{CURRENT_CLUSTER_NAME}}
spec:
  data: |
    security:
      passwords_secret_name: pgxl-passwords-collection
      pg_password: pgpass
