apiVersion: {{CUSTOM_RESOURCE_GROUP}}/v1
kind: {{CLUSTER_RESOURCE_KIND}}
metadata:
  name: {{CURRENT_CLUSTER_NAME}}
spec:
  data: |
    on_load:
      enabled: true
      startup:
        - name: create_database.sh
          content: |-
            psql -c "CREATE DATABASE tester;"
            export PGDATABASE="tester"
        - name: create_base_tables.sql
          content: |-
            CREATE SCHEMA test;
            CREATE TABLE test.lama as (SELECT 'the brown rabbit' as col_1);
      init:
        - name: create_database.sh
          content: |-
            psql -c "CREATE DATABASE tester;"
            export PGDATABASE="tester"
        - name: create_base_tables.sql
          content: |-
            CREATE SCHEMA test;
            CREATE TABLE test.lama as (SELECT 'the brown rabbit' as col_1);