apiVersion: {{CUSTOM_RESOURCE_GROUP}}/v1
kind: {{CLUSTER_RESOURCE_KIND}}
metadata:
  name: {{CURRENT_CLUSTER_NAME}}
spec:
  data: |
    security:
      password:
        method: operator
    connection_pool:
      enabled: true
