apiVersion: {{CUSTOM_RESOURCE_GROUP}}/v1
kind: {{CLUSTER_RESOURCE_KIND}}
metadata:
  name: {{CURRENT_CLUSTER_NAME}}
spec:
  data: |
    replication:
      enabled: true
      master_name: {{CURRENT_CLUSTER_NAME}}
      slave_name: slave1